/*
 * Forest.h
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#ifndef FOREST_H_
#define FOREST_H_

#include "Card_Land.h"

class Forest: public Card_Land {
public:
	Forest();
	virtual ~Forest();
	string GetImage();
	void Play();
};

#endif /* FOREST_H_ */

