/*
 * Mountain.h
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#ifndef MOUNTAIN_H_
#define MOUNTAIN_H_

#include "Card_Land.h"

class Mountain: public Card_Land {
public:
	Mountain();
	virtual ~Mountain();
	string GetImage();
	void Play();
};

#endif /* MOUNTAIN_H_ */

