/*
 * Mountain.cpp
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#include "Mountain.h"

Mountain::Mountain() {
	KeywordVanilla();
	id = 376418;
	name = "Mountain";
	cmc = 0;
	isBasic = true;
	isLand = true;
	subtype.push_back("Mountain");
	rulesText.push_back("R");
	power = 0;
	toughness = 0;
	loyalty = 0;
	set = "Commander 2013 Edition";
	rarity = "Basic Land";
	cardNumber = 351;
	image = "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=376418&type=card";

	DefaultInit();
}

Mountain::~Mountain() {
}

string Mountain::GetImage() {
	return "|R|";
}

void Mountain::Play() {
	MoveLoc(thePlayer->bf);
	thePlayer->maxMana[colors::R]++;
	thePlayer->curMana[colors::R]++;
}

