/*
 * Plains.cpp
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#include "Plains.h"

Plains::Plains() {
	KeywordVanilla();
	id = 376451;
	name = "Plains";
	cmc = 0;
	isLand = true;
	isBasic = true;
	subtype.push_back("Plains");
	rulesText.push_back("W");
	power = 0;
	toughness = 0;
	loyalty = 0;
	set = "Commander 2013 Edition";
	rarity = "Basic Land";
	cardNumber = 339;
	image = "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=376451&type=card";
}

Plains::~Plains() {
}

string Plains::GetImage() {
	return "|W|";
}

void Plains::Play() {
	MoveLoc(thePlayer->bf);
	thePlayer->maxMana[colors::W]++;
	thePlayer->curMana[colors::W]++;
}

