/*
 * Plains.h
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#ifndef PLAINS_H_
#define PLAINS_H_

#include "Card_Land.h"

class Plains: public Card_Land {
public:
	Plains();
	virtual ~Plains();
	string GetImage();
	void Play();
};

#endif /* PLAINS_H_ */

