/*
 * AzureDrake.h
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#ifndef AZUREDRAKE_H_
#define AZUREDRAKE_H_

#include "Card_Creature.h"

class AzureDrake: public Card_Creature {
public:
	AzureDrake();
	virtual ~AzureDrake();
};

#endif /* AZUREDRAKE_H_ */

