/*
 * AzureDrake.cpp
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#include "AzureDrake.h"

AzureDrake::AzureDrake() {
	KeywordVanilla();
	id = 204984;
	name = "Azure Drake";
	cmc = 4;
	isCreature = true;
	subtype.push_back("Drake");
	flying = true;
	flavor.push_back("More so than \"storm\" or \"pirate,\" \"drake\" is the word a sailor least wants to hear.");
	power = 2;
	toughness = 4;
	loyalty = 0;
	set = "Magic 2011";
	rarity = "Common";
	cardNumber = 46;
	image = "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=204984&type=card";
	mana[colors::O]+=3;
	mana[colors::U]++;

	InitDefault();
}

AzureDrake::~AzureDrake() {
}

