/*
 * BlindPhantasm.h
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#ifndef BLINDPHANTASM_H_
#define BLINDPHANTASM_H_

#include "Card_Creature.h"

class BlindPhantasm: public Card_Creature {
public:
	BlindPhantasm();
	virtual ~BlindPhantasm();
};

#endif /* BLINDPHANTASM_H_ */

