/*
 * BlindPhantasm.cpp
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#include "BlindPhantasm.h"

BlindPhantasm::BlindPhantasm() {
	KeywordVanilla();
	id = 126143;
	name = "Blind Phantasm";
	cmc = 3;
	isCreature = true;
	subtype.push_back("Illusion");
	power = 2;
	toughness = 3;
	loyalty = 0;
	set = "Future Sight";
	rarity = "Common";
	cardNumber = 49;
	image = "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=126143&type=card";
	mana[colors::O]+=2;
	mana[colors::U]++;

	InitDefault();
}

BlindPhantasm::~BlindPhantasm() {
}

