/*
 * CoralMerfolk.h
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#ifndef CORALMERFOLK_H_
#define CORALMERFOLK_H_

#include "Card_Creature.h"

class CoralMerfolk: public Card_Creature {
public:
	CoralMerfolk();
	virtual ~CoralMerfolk();
};

#endif /* CORALMERFOLK_H_ */

