/*
 * FlyingMen.h
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#ifndef FLYINGMEN_H_
#define FLYINGMEN_H_

#include "Card_Creature.h"

class FlyingMen: public Card_Creature {
public:
	FlyingMen();
	virtual ~FlyingMen();
};

#endif /* FLYINGMEN_H_ */

