/*
 * GoliathSphinx.h
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#ifndef GOLIATHSPHINX_H_
#define GOLIATHSPHINX_H_

#include "Card_Creature.h"

class GoliathSphinx: public Card_Creature {
public:
	GoliathSphinx();
	virtual ~GoliathSphinx();
};

#endif /* GOLIATHSPHINX_H_ */

