/*
 * HornedTurtle.h
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#ifndef HORNEDTURTLE_H_
#define HORNEDTURTLE_H_

#include "Card_Creature.h"

class HornedTurtle: public Card_Creature {
public:
	HornedTurtle();
	virtual ~HornedTurtle();
};

#endif /* HORNEDTURTLE_H_ */

