/*
 * PhantomWarrior.h
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#ifndef PHANTOMWARRIOR_H_
#define PHANTOMWARRIOR_H_

#include "Card_Creature.h"

class PhantomWarrior: public Card_Creature {
public:
	PhantomWarrior();
	virtual ~PhantomWarrior();
};

#endif /* PHANTOMWARRIOR_H_ */

