/*
 * PhantomWarrior.cpp
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#include "PhantomWarrior.h"

PhantomWarrior::PhantomWarrior() {
	KeywordVanilla();
	id = 370650;
	name = "Phantom Warrior";
	cmc = 3;
	isCreature = true;
	subtype.push_back("Illusion");
	subtype.push_back("Warrior");
	unblockable = true;
	flavor.push_back("\"The construction of a defense is not accomplished by adding bricks.\"--Jace Beleren");
	power = 2;
	toughness = 2;
	loyalty = 0;
	set = "Magic 2014 Core Set";
	rarity = "Uncommon";
	cardNumber = 67;
	image = "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=370650&type=card";
	mana[colors::O]+=1;
	mana[colors::U]++;
	color[colors::U] = true;
	mana[colors::U]++;
	color[colors::U] = true;

	DefaultInit();
}

PhantomWarrior::~PhantomWarrior() {
}

