/*
 * AirElemental.h
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#ifndef AIRELEMENTAL_H_
#define AIRELEMENTAL_H_

#include "Card_Creature.h"

class AirElemental: public Card_Creature {
public:
	AirElemental();
	virtual ~AirElemental();
};

#endif /* AIRELEMENTAL_H_ */

