/*
 * AxebaneStag.h
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#ifndef AXEBANESTAG_H_
#define AXEBANESTAG_H_

#include "Card_Creature.h"

class AxebaneStag: public Card_Creature {
public:
	AxebaneStag();
	virtual ~AxebaneStag();
};

#endif /* AXEBANESTAG_H_ */

