/*
 * CoralMerfolk.cpp
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#include "CoralMerfolk.h"

CoralMerfolk::CoralMerfolk() {
	KeywordVanilla();
	id = 370667;
	name = "Coral Merfolk";
	cmc = 2;
	isCreature = true;
	subtype.push_back("Merfolk");
	flavor.push_back("Early sailors thought they were tricks of the mind or perhaps manatees. As more and more ships were classified as lost to \"manatee attacks,\" the truth began to dawn.");
	power = 2;
	toughness = 1;
	loyalty = 0;
	set = "Magic 2014 Core Set";
	rarity = "Common";
	cardNumber = 49;
	image = "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=370667&type=card";
	mana[colors::O]+=1;
	mana[colors::U]++;
	color[colors::U] = true;

	DefaultInit();
}

CoralMerfolk::~CoralMerfolk() {
}

