/*
 * CrawWurm.cpp
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#include "CrawWurm.h"

CrawWurm::CrawWurm() {
	KeywordVanilla();
	id = 189903;
	name = "Craw Wurm";
	cmc = 6;
	isCreature = true;
	subtype.push_back("Wurm");
	flavor.push_back("The most terrifying thing about the craw wurm is probably the horrible crashing sound it makes as it speeds through the forest. This noise is so loud it echoes through the trees and seems to come from all directions at once.");
	power = 6;
	toughness = 4;
	loyalty = 0;
	set = "Magic 2010";
	rarity = "Common";
	cardNumber = 173;
	image = "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=189903&type=card";
	mana[colors::O]+=4;
	mana[colors::G]++;
	color[colors::G] = true;
	mana[colors::G]++;
	color[colors::G] = true;

	DefaultInit();
}

CrawWurm::~CrawWurm() {
}

