/*
 * CrawWurm.h
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#ifndef CRAWWURM_H_
#define CRAWWURM_H_

#include "Card_Creature.h"

class CrawWurm: public Card_Creature {
public:
	CrawWurm();
	virtual ~CrawWurm();
};

#endif /* CRAWWURM_H_ */

