/*
 * FlyingMen.cpp
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#include "FlyingMen.h"

FlyingMen::FlyingMen() {
	KeywordVanilla();
	id = 107291;
	name = "Flying Men";
	cmc = 1;
	isCreature = true;
	subtype.push_back("Human");
	flying = true;
	flavor.push_back("Saffiyah clapped her hands and twenty flying men appeared at her side, each well trained in the art of combat.");
	power = 1;
	toughness = 1;
	loyalty = 0;
	set = "Time Spiral \"Timeshifted\"";
	rarity = "Special";
	cardNumber = 20;
	image = "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=107291&type=card";
	mana[colors::U]++;
	color[colors::U] = true;

	DefaultInit();
}

FlyingMen::~FlyingMen() {
}

