/*
 * GoliathSphinx.cpp
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#include "GoliathSphinx.h"

GoliathSphinx::GoliathSphinx() {
	KeywordVanilla();
	id = 197153;
	name = "Goliath Sphinx";
	cmc = 7;
	isCreature = true;
	subtype.push_back("Sphinx");
	flying = true;
	flavor.push_back("He makes his home on the tallest mountain in Sejiri, where the vista is as endless as his patience.");
	power = 8;
	toughness = 7;
	loyalty = 0;
	set = "Worldwake";
	rarity = "Rare";
	cardNumber = 28;
	image = "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=197153&type=card";
	mana[colors::O]+=5;
	mana[colors::U]++;
	mana[colors::U]++;

	InitDefault();
}

GoliathSphinx::~GoliathSphinx() {
}

