/*
 * HollowhengeBeast.h
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#ifndef HOLLOWHENGEBEAST_H_
#define HOLLOWHENGEBEAST_H_

#include "Card_Creature.h"

class HollowhengeBeast: public Card_Creature {
public:
	HollowhengeBeast();
	virtual ~HollowhengeBeast();
};

#endif /* HOLLOWHENGEBEAST_H_ */

