/*
 * KrakenHatchling.h
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#ifndef KRAKENHATCHLING_H_
#define KRAKENHATCHLING_H_

#include "Card_Creature.h"

class KrakenHatchling: public Card_Creature {
public:
	KrakenHatchling();
	virtual ~KrakenHatchling();
};

#endif /* KRAKENHATCHLING_H_ */

