/*
 * NorwoodRanger.h
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#ifndef NORWOODRANGER_H_
#define NORWOODRANGER_H_

#include "Card_Creature.h"

class NorwoodRanger: public Card_Creature {
public:
	NorwoodRanger();
	virtual ~NorwoodRanger();
};

#endif /* NORWOODRANGER_H_ */

