/*
 * PheresBandCentaurs.cpp
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#include "PheresBandCentaurs.h"

PheresBandCentaurs::PheresBandCentaurs() {
	KeywordVanilla();
	id = 373657;
	name = "Pheres-Band Centaurs";
	cmc = 5;
	isCreature = true;
	subtype.push_back("Centaur");
	subtype.push_back("Warrior");
	flavor.push_back("\"Poets speak of your unrivaled speed,\" the Champion said to the assembled centaurs, \"but it is plain to see that your true strength lies in your unwavering loyalty to one another.\"");
	flavor.push_back("--The Theriad");
	power = 3;
	toughness = 7;
	loyalty = 0;
	set = "Theros";
	rarity = "Common";
	cardNumber = 171;
	image = "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=373657&type=card";
	mana[colors::O]+=4;
	mana[colors::G]++;

	InitDefault();
}

PheresBandCentaurs::~PheresBandCentaurs() {
}

