/*
 * PheresBandCentaurs.h
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#ifndef PHERESBANDCENTAURS_H_
#define PHERESBANDCENTAURS_H_

#include "Card_Creature.h"

class PheresBandCentaurs: public Card_Creature {
public:
	PheresBandCentaurs();
	virtual ~PheresBandCentaurs();
};

#endif /* PHERESBANDCENTAURS_H_ */

