/*
 * RumblingBaloth.h
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#ifndef RUMBLINGBALOTH_H_
#define RUMBLINGBALOTH_H_

#include "Card_Creature.h"

class RumblingBaloth: public Card_Creature {
public:
	RumblingBaloth();
	virtual ~RumblingBaloth();
};

#endif /* RUMBLINGBALOTH_H_ */

