/*
 * ScaledWurm.h
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#ifndef SCALEDWURM_H_
#define SCALEDWURM_H_

#include "Card_Creature.h"

class ScaledWurm: public Card_Creature {
public:
	ScaledWurm();
	virtual ~ScaledWurm();
};

#endif /* SCALEDWURM_H_ */

