/*
 * SeacoastDrake.h
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#ifndef SEACOASTDRAKE_H_
#define SEACOASTDRAKE_H_

#include "Card_Creature.h"

class SeacoastDrake: public Card_Creature {
public:
	SeacoastDrake();
	virtual ~SeacoastDrake();
};

#endif /* SEACOASTDRAKE_H_ */

