/*
 * SeacoastDrake.cpp
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#include "SeacoastDrake.h"

SeacoastDrake::SeacoastDrake() {
	KeywordVanilla();
	id = 370617;
	name = "Seacoast Drake";
	cmc = 2;
	isCreature = true;
	subtype.push_back("Drake");
	flying = true;
	flavor.push_back("Seacoast drakes have been known to follow ships for hundreds of miles, waiting to snap up garbage, bait, and the occasional sailor.");
	power = 1;
	toughness = 3;
	loyalty = 0;
	set = "Magic 2014 Core Set";
	rarity = "Common";
	cardNumber = 70;
	image = "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=370617&type=card";
	mana[colors::O]+=1;
	mana[colors::U]++;
	color[colors::U] = true;

	DefaultInit();
}

SeacoastDrake::~SeacoastDrake() {
}

