/*
 * SkylinePredator.cpp
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#include "SkylinePredator.h"

SkylinePredator::SkylinePredator() {
	KeywordVanilla();
	id = 289212;
	name = "Skyline Predator";
	cmc = 6;
	isCreature = true;
	subtype.push_back("Drake");
	flash = true;
	flying = true;
	flavor.push_back("\"It will dodge your first arrow and flatten you before there\'s a second.\"");
	flavor.push_back("--Alcarus, Selesnya archer");
	power = 3;
	toughness = 4;
	loyalty = 0;
	set = "Return to Ravnica";
	rarity = "Uncommon";
	cardNumber = 50;
	image = "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=289212&type=card";
	mana[colors::O]+=4;
	mana[colors::U]++;
	mana[colors::U]++;

	InitDefault();
}

SkylinePredator::~SkylinePredator() {
}

