/*
 * SkylinePredator.h
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#ifndef SKYLINEPREDATOR_H_
#define SKYLINEPREDATOR_H_

#include "Card_Creature.h"

class SkylinePredator: public Card_Creature {
public:
	SkylinePredator();
	virtual ~SkylinePredator();
};

#endif /* SKYLINEPREDATOR_H_ */

