/*
 * SnappingDrake.cpp
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#include "SnappingDrake.h"

SnappingDrake::SnappingDrake() {
	KeywordVanilla();
	id = 190163;
	name = "Snapping Drake";
	cmc = 4;
	isCreature = true;
	subtype.push_back("Drake");
	flying = true;
	flavor.push_back("Foul-tempered, poorly trained, and mule-stubborn, the drake is the perfect test of the master\'s will.");
	power = 3;
	toughness = 2;
	loyalty = 0;
	set = "Magic 2010";
	rarity = "Common";
	cardNumber = 72;
	image = "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=190163&type=card";
	mana[colors::O]+=3;
	mana[colors::U]++;

	InitDefault();
}

SnappingDrake::~SnappingDrake() {
}

