/*
 * SnappingDrake.h
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#ifndef SNAPPINGDRAKE_H_
#define SNAPPINGDRAKE_H_

#include "Card_Creature.h"

class SnappingDrake: public Card_Creature {
public:
	SnappingDrake();
	virtual ~SnappingDrake();
};

#endif /* SNAPPINGDRAKE_H_ */

