/*
 * SpinedWurm.h
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#ifndef SPINEDWURM_H_
#define SPINEDWURM_H_

#include "Card_Creature.h"

class SpinedWurm: public Card_Creature {
public:
	SpinedWurm();
	virtual ~SpinedWurm();
};

#endif /* SPINEDWURM_H_ */

