/*
 * VastwoodGorger.h
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#ifndef VASTWOODGORGER_H_
#define VASTWOODGORGER_H_

#include "Card_Creature.h"

class VastwoodGorger: public Card_Creature {
public:
	VastwoodGorger();
	virtual ~VastwoodGorger();
};

#endif /* VASTWOODGORGER_H_ */

