/*
 * WindDrake.h
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#ifndef WINDDRAKE_H_
#define WINDDRAKE_H_

#include "Card_Creature.h"

class WindDrake: public Card_Creature {
public:
	WindDrake();
	virtual ~WindDrake();
};

#endif /* WINDDRAKE_H_ */

