/*
 * AxebaneStag.cpp
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#include "AxebaneStag.h"

AxebaneStag::AxebaneStag() {
	KeywordVanilla();
	id = 265383;
	name = "Axebane Stag";
	cmc = 7;
	isCreature = true;
	subtype.push_back("Elk");
	flavor.push_back("\"When the spires have burned and the cobblestones are dust, he will take his rightful place as king of the wilds.\"");
	flavor.push_back("--Kirce, Axebane guardian");
	power = 6;
	toughness = 7;
	loyalty = 0;
	set = "Return to Ravnica";
	rarity = "Common";
	cardNumber = 116;
	image = "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=265383&type=card";
	mana[colors::O]+=6;
	mana[colors::G]++;

	InitDefault();
}

AxebaneStag::~AxebaneStag() {
}

