/*
 * GrizzlyBears.cpp
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#include "GrizzlyBears.h"

GrizzlyBears::GrizzlyBears() {
	KeywordVanilla();
	id = 129586;
	name = "Grizzly Bears";
	cmc = 2;
	isCreature = true;
	subtype.push_back("Bear");
	flavor.push_back("\"We cannot forget that among all of Dominaria\'s wonders, a system of life exists, with prey and predators that will never fight wars nor vie for ancient power.\"");
	flavor.push_back("--Jolrael, empress of beasts");
	power = 2;
	toughness = 2;
	loyalty = 0;
	set = "Tenth Edition";
	rarity = "Common";
	cardNumber = 268;
	image = "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129586&type=card";
	mana[colors::O]+=1;
	mana[colors::G]++;

	InitDefault();
}

GrizzlyBears::~GrizzlyBears() {
}

