/*
 * HollowhengeBeast.cpp
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#include "HollowhengeBeast.h"

HollowhengeBeast::HollowhengeBeast() {
	KeywordVanilla();
	id = 262868;
	name = "Hollowhenge Beast";
	cmc = 5;
	isCreature = true;
	subtype.push_back("Beast");
	flavor.push_back("In a world of monsters, it\'s the stuff of nightmares.");
	power = 5;
	toughness = 5;
	loyalty = 0;
	set = "Dark Ascension";
	rarity = "Common";
	cardNumber = 118;
	image = "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=262868&type=card";
	mana[colors::O]+=3;
	mana[colors::G]++;
	color[colors::G] = true;
	mana[colors::G]++;
	color[colors::G] = true;

	DefaultInit();
}

HollowhengeBeast::~HollowhengeBeast() {
}

