/*
 * NessianCourser.h
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#ifndef NESSIANCOURSER_H_
#define NESSIANCOURSER_H_

#include "Card_Creature.h"

class NessianCourser: public Card_Creature {
public:
	NessianCourser();
	virtual ~NessianCourser();
};

#endif /* NESSIANCOURSER_H_ */

