/*
 * NettleSwine.cpp
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#include "NettleSwine.h"

NettleSwine::NettleSwine() {
	KeywordVanilla();
	id = 239978;
	name = "Nettle Swine";
	cmc = 4;
	isCreature = true;
	subtype.push_back("Boar");
	flavor.push_back("\"I killed one and found bricks and bones in its belly. It had eaten a whole cottage, thatch and all.\"");
	flavor.push_back("--Paulin, Somberwald trapper");
	power = 4;
	toughness = 3;
	loyalty = 0;
	set = "Avacyn Restored";
	rarity = "Common";
	cardNumber = 186;
	image = "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=239978&type=card";
	mana[colors::O]+=3;
	mana[colors::G]++;
	color[colors::G] = true;

	DefaultInit();
}

NettleSwine::~NettleSwine() {
}

