/*
 * NettleSwine.h
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#ifndef NETTLESWINE_H_
#define NETTLESWINE_H_

#include "Card_Creature.h"

class NettleSwine: public Card_Creature {
public:
	NettleSwine();
	virtual ~NettleSwine();
};

#endif /* NETTLESWINE_H_ */

