/*
 * NorwoodRanger.cpp
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#include "NorwoodRanger.h"

NorwoodRanger::NorwoodRanger() {
	KeywordVanilla();
	id = 83188;
	name = "Norwood Ranger";
	cmc = 1;
	isCreature = true;
	subtype.push_back("Elf");
	subtype.push_back("Scout");
	flavor.push_back("The song of the forest is in perfect harmony. If a single note is out of place, the elves will find its source.");
	power = 1;
	toughness = 2;
	loyalty = 0;
	set = "Ninth Edition";
	rarity = "Common";
	cardNumber = 260;
	image = "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=83188&type=card";
	mana[colors::G]++;

	InitDefault();
}

NorwoodRanger::~NorwoodRanger() {
}

