/*
 * SpinedWurm.cpp
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#include "SpinedWurm.h"

SpinedWurm::SpinedWurm() {
	KeywordVanilla();
	id = 205123;
	name = "Spined Wurm";
	cmc = 5;
	isCreature = true;
	subtype.push_back("Wurm");
	flavor.push_back("\"They\'re as much like plants as animals. Leave them unchecked, and they\'ll choke out all other forms of life.\"");
	flavor.push_back("--Hadi Kasten, Calla Dale naturalist");
	power = 5;
	toughness = 4;
	loyalty = 0;
	set = "Magic 2011";
	rarity = "Common";
	cardNumber = 197;
	image = "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=205123&type=card";
	mana[colors::O]+=4;
	mana[colors::G]++;
	color[colors::G] = true;

	DefaultInit();
}

SpinedWurm::~SpinedWurm() {
}

