/*
 * VastwoodGorger.cpp
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#include "VastwoodGorger.h"

VastwoodGorger::VastwoodGorger() {
	KeywordVanilla();
	id = 279992;
	name = "Vastwood Gorger";
	cmc = 6;
	isCreature = true;
	subtype.push_back("Wurm");
	flavor.push_back("\"A long and difficult incision revealed that all vital organs are housed in the head, save for a long chain of stomachs, forty in all, leading from its throat to the end of the tail.\"");
	flavor.push_back("--Mulak Ffar, Vastwood Biodiversity");
	power = 5;
	toughness = 6;
	loyalty = 0;
	set = "Magic 2013";
	rarity = "Common";
	cardNumber = 196;
	image = "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=279992&type=card";
	mana[colors::O]+=5;
	mana[colors::G]++;
	color[colors::G] = true;

	DefaultInit();
}

VastwoodGorger::~VastwoodGorger() {
}

