/*
 * GrizzlyBears.h
 *
 * Autogenerated by generateCards.py
 *	Author: dstuck
*/

#ifndef GRIZZLYBEARS_H_
#define GRIZZLYBEARS_H_

#include "Card_Creature.h"

class GrizzlyBears: public Card_Creature {
public:
	GrizzlyBears();
	virtual ~GrizzlyBears();
};

#endif /* GRIZZLYBEARS_H_ */

